# Generated by Django 2.0.3 on 2018-04-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sellinfo',
            fields=[
                ('houseid', models.CharField(db_column='houseID', max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('community', models.CharField(max_length=255)),
                ('years', models.CharField(max_length=255)),
                ('housetype', models.CharField(max_length=255)),
                ('square', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
                ('floor', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('totalprice', models.CharField(db_column='totalPrice', max_length=255)),
                ('unitprice', models.CharField(db_column='unitPrice', max_length=255)),
                ('dealdate', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedate', models.DateTimeField()),
            ],
            options={
                'db_table': 'sellinfo',
                'managed': False,
            },
        ),
    ]
